### ISSUE TITLE
Non-ASCII character '\xc2' in file ( escape_table.py )

### ISSUE THREAD

**Issue by dsole** [colinta/SublimeStringEncode#23]
After a recent update I now get this error in the console. I'm on Windows 7 64 bit with Sublime Text 2.0.2

	
	Reloading plugin C:\Users\soled\AppData\Roaming\Sublime Text 2\Packages\StringEncode\string_encode.py
	Traceback (most recent call last):
	  File ".\sublime_plugin.py", line 62, in reload_plugin
	    m = imp.load_module(modulename, *m_info)
	  File ".\string_encode.py", line 10, in <module>
	    from stringencode.escape_table import (
	  File ".\stringencode\escape_table.py", line 6
	SyntaxError: Non-ASCII character '\xc2' in file .\stringencode\escape_table.py on line 6, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by colinta** [comment]
I added `# coding: utf8` to that file.  Thanks for reporting it!

**Comment by dsole** [comment]
Thank you !

**Comment by shashiRS** [comment]
Thank You, it works fine!
