### ISSUE TITLE
URL Decode delete [+] symbol

### ISSUE THREAD

**Issue by Kristinita** [colinta/SublimeStringEncode#26]
![plus](https://cloud.githubusercontent.com/assets/17247677/14530657/9d5ac7bc-0262-11e6-85aa-c853c569b5df.gif)

**Comment by colinta** [comment]
Thanks for the video!  This is not a bug, though, the `+` sign *is* a space in URLs.

Encoding a space can go one of two ways: either `%20` (ASCII 32) or `+`.  When encoding a `+`, though, it is *always* `%2B` (ASCII 43).

When decoding, though, the `+` will *always decode into a space.

**Comment by Kristinita** [comment]
But documents often contain the text with a symbol `+` which isn't a part of URL. Its removal can strongly do much harm to contents of files.

I suggest to replace `+` → ` ` only in a case when the symbol `+` is a part of URL, but in other cases not to delete it. 

Thanks.

**Comment by colinta** [comment]
I don't understand - why are you decoding documents that *aren't* URLs?  The whole point is to take a url like `https://www.google.com/?q=this%3Ais+a%20%2Asilly%2A%20example%21` and decode it into `https://www.google.com/?q=this:is a *silly* example!`.

**Comment by colinta** [comment]
I think I might see what's going on - you're wanting it to decode URLs *in* a document?  I just noticed that you didn't make any selection, in which case it defaults to "the entire document".  But it doesn't try to detect what is a URL and what isn't (and I don't would not want to maintain a "detect URL" feature for such a simple plugin).

Instead, select the URLs manually, and then run the plugin, and it will only transform the selection(s).

**Comment by Kristinita** [comment]
> I don't understand - why are you decoding documents that aren't URLs? 

No, I decode documents contains many URL and many other text.

> Instead, select the URLs manually, and then run the plugin, and it will only transform the selection(s).

If the document big and contains in it many URL, it will take away a lot of time and forces.

Thanks.

**Comment by colinta** [comment]
You can make this really easy by using regex search and "Find All"

![url decode demo](https://cloud.githubusercontent.com/assets/27570/14537468/5a7724d2-0234-11e6-8649-ca79f2e665f0.gif)

If you're hoping that I'll take the time to add this feature that you want, I'm afraid I must disappoint.  This can be accomplished very easily using multiple selections, so there's no point in adding this "feature" (I don't think it's a feature, because detecting URLs like `This -> github.com <- url` would be a PITA).

**Comment by colinta** [comment]
Oops, that video got truncated!  One sec.

**Comment by colinta** [comment]
![url decode demo](https://cloud.githubusercontent.com/assets/27570/14537567/c0684c62-0234-11e6-86a0-f19f3f3b6969.gif)

**Comment by Kristinita** [comment]
If you don't wish to correct, in my opinion, it is necessary to specify obviously that in the text which isn't containing URL is removed `+`, in [`README.md`](https://github.com/colinta/SublimeStringEncode/blob/master/README.md) as the problem can seriously do much harm to documents of users, and people can not understand at once that `+` StringEncode is the reason of removal. Thanks.

**Comment by colinta** [comment]
> seriously do much harm

This is very melodramatic.  You can undo that operation.  If you want this plugin to work differently, please fork it, change it, and be happy!

I've updated the README to warn against using it the way you are describing:

2d7196e02aecfe32917458c0e61555dff8887b32
