### ISSUE TITLE
Port to Cuda

### ISSUE THREAD

**Issue by Alexey-T** [colinta/SublimeStringEncode#28]
Hi, useful plugin. I want to use parts in my plugin (not for ST3). Can you help? i need some refactor of your code: ie make functions like

    def do_convert(text_from, coding_name) # gets string

**Comment by Alexey-T** [comment]
Solved;i will make port; tkx

**Comment by Alexey-T** [comment]
Solved, port is https://sourceforge.net/projects/cudatext/files/addons/plugins/plugin.Encode.zip/download

**Comment by colinta** [comment]
That's awesome!
