### ISSUE TITLE
Decode XHTML/XML numeric character references

### ISSUE THREAD

**Issue by elmimmo** [colinta/SublimeStringEncode#31]
`html_deentitize` and `xml_deentitize` should decode [numeric character references](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Character_reference_overview) but they don't.

**Comment by colinta** [comment]
Can you paste some examples of characters you expected to have encoded?

**Comment by elmimmo** [comment]
For instance, `&#931;` should decode to `Σ` with both `html_deentitize` and `xml_deentitize`.

The Hasher module, installable via Package Manager, has the menu command "Hasher: Entity Decode" which does convert that to a greek letter just fine.

**Comment by oleg-babintsev** [comment]
+1
Problem is actual for me too.

**Comment by colinta** [comment]
Ah gotcha, I didn't have support for decimal encoding (`&#931;` == `&#x3a3;`, which does deentitize as expected).  Fixed in 2.2.3.
