### ISSUE TITLE
unnkown encoding results > a&#x308

### ISSUE THREAD

**Issue by katerlouis** [colinta/SublimeStringEncode#32]
I copy and paste text out of a pdf from my text guru.
When I encode it I get `a&#x308` instead of `&auml;`.
The same goes for `ü > u&#x308` and `ö > o&#x308`.

A `ß` encodes `&szlig` as expected, though.

What's going on! I the usual `&auml;` back. 
This new format is killing my webfont and replacing all the `a&#x308` is a huge pain :(

**Comment by colinta** [comment]
Can you send me the text you're copying and trying to paste?

Does the encoding work when you paste the text (as is), and then select it and encode it (e.g. the "old fashioned way")?

**Comment by colinta** [comment]
I just tried it w/ `über` and it pasted `&uuml;ber`, which seems right to me... are you using the `XML` or `HTML` entities?

**Comment by katerlouis** [comment]
Wtf, that was fast :o
I'm sure it is an issue of the Word export to pdf, or a Word setting. 
Your plugin isn't the problem; the default encoding function produces the same weird results. I have no other place to go! Google always deletes the `a&#x308` :D  – So I figured maybe it's a common issue you might know.

I do not follow your "old fashioned way", though.
Here is a sample of the pdf I copy from.

[paste-problem-sample.pdf](https://github.com/colinta/SublimeStringEncode/files/350171/paste-problem-sample.pdf)

**Comment by katerlouis** [comment]
When I type `über` inside the editor and encode it, I get `&uuml;` aswell. 
"Where do I use XML or HTML entities?" – Sorry for my ignorance, but the deadline is so freakin close I lose my mind! :D

**Comment by colinta** [comment]
There are two "entitize" commands, one for XML and one for HTML.  You're using the right one, I think.

I have an idea: paste the text somewhere in github (in a comment here) and then copy it FROM your browser. On my computer, at least, that fixes these characters.

**Comment by colinta** [comment]
Mitten in einer grünen Oase, am südlichen Berliner Stadtrand, befindet sich unsere Senioren-Residenz Lore Lipschitz. Umgeben von einem weitläufigen, barrierefreien, geschützten Garten mit gemütlichen Pavillons, können unsere Bewohner die sorglose Ruhe der Natur oder ein gemütliches Beisammensein an der frischen Luft genießen - ganz wie sie es ihnen beliebt.

```
Mitten in einer gr&uuml;nen Oase, am s&uuml;dlichen Berliner Stadtrand, befindet sich unsere Senioren-Residenz Lore Lipschitz. Umgeben von einem weitl&auml;ufigen, barrierefreien, gesch&uuml;tzten Garten mit gem&uuml;tlichen Pavillons, k&ouml;nnen unsere Bewohner die sorglose Ruhe der Natur oder ein gem&uuml;tliches Beisammensein an der frischen Luft genie&szlig;en - ganz wie sie es ihnen beliebt.
```

**Comment by colinta** [comment]
When I copy/paste directly from the pdf, I get the same garbage you're talking about:

```
Mitten in einer gru&#x308;nen Oase, am su&#x308;dlichen
```

**Comment by katerlouis** [comment]
Sweet, isn't it?
My google skillz are too low, I can't find shit about it :( – I'm desperate.
All I know this pdf is produced by Word from Office 360 on a Windows 10 laptop.
We played around with the exporting options, but.. I'm still here ;)

**Comment by colinta** [comment]
Did you try my idea?  Copy all the text you need to convert and paste in *here in github*.  You don't have to submit it, just click "Preview" and then copy the text again.

When you `Paste Encoded… > Html entitize` that text, it will have the correct HTML entities.

**Comment by katerlouis** [comment]
As you see there is this table layout in the PDF, copying all somewhere is far away from ideal. I have multiple files and stuff. Hm. There must be a setting in Wordpress... some UTF8-encoding what ever shits :D

**Comment by katerlouis** [comment]
Wait, so you are sure, that it has to do with the table?

**Comment by katerlouis** [comment]
WTF DID MY EYES JUST SEE? 
You implemented my idea with paste encoding? :D
Why don't I have that already?!!

Back to topic:
I'm not looking for a workaround; I guess in that case it would be faster to replace the whole project with sublime texts replace feature.

If you don't know how to fix the source of the problem I'll go with replacing :(
Thanks! Very much.

And now tell me about the paste encoded thing :D

**Comment by colinta** [comment]
I have no idea what the source of the problem is - you have mentioned wordpress (which I never use), Office 360 (which I never use), and Windows (which I never use).

┐(ﾟ～ﾟ)┌

**Comment by katerlouis** [comment]
I meant Word :D and corrected it immediately. But you are just too fast.
But seriously. **Where is this "paste encoded function" and what is the sublime-function-name so I can bind it! :D**

**Comment by katerlouis** [comment]
I just saw your reply on my issue.. damn whats going on with me :D
My brain is mudged.

How can I update inside of Sublime Text without removing and reinstalling?
And I'm curious how to see the current version of a plugin.

**Comment by colinta** [comment]
Are you using Package Control?  It will auto-update your packages (daily, I think).  To force an upgrade:

1. `Tools > Command Palette` to view all the commands (you can search for "StringEncode" commands there, btw)
2. Type `PC Upgrade` (to filter to "Package Control: Upgrade") and then `StringEncode` to upgrade
3. or type `PC List` to show the version numbers
