### ISSUE TITLE
Base64 Decode requires padding

### ISSUE THREAD

**Issue by scholtes** [colinta/SublimeStringEncode#37]
Base64 Decode will not decode strings with the padding characters removed.  

As the padding characters are technically not required to decode without ambiguity, many applications strip the padding after encoding.  

A quick fix would be to change the following line ([here](https://github.com/colinta/SublimeStringEncode/blob/6d07eb74d4861979e5f05f60138302145b1bf379/string_encode.py#L273)): 

```
return base64.b64decode(text).decode('raw_unicode_escape')
```

to this: 

```
return base64.b64decode(text + '===').decode('raw_unicode_escape')
```

(Per [this gist](https://gist.github.com/perrygeo/ee7c65bb1541ff6ac770), excess padding is safely ignored.  More tips and tricks in that link).

A Sublime user can work around this by manually typing in the padding before using this feature, but I think adding this redundancy could benefit the overall ease of use (and hopefully not [break anyone's workflow](https://xkcd.com/1172/)).

**Comment by colinta** [comment]
A pull request would be most welcome!  I'll try to add this fix, but it hasn't come up before.
